name: Md5 Generator

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: MCJack123/ghaction-Generate-Release-Hashes@v1
      with:
        hash-type: sha256
        file-name: hashes.txt
    - uses: actions/upload-artifact@v2
      with:
        name: Asset Hashes
        path: hashes.txt